"Vim rc
"Set Leader Key to Space
map <space> <leader>
map <leader>A ggVG

nmap <c-s> :w<CR>
imap <c-s> <Esc>:w<CR>

"Plug 
call plug#begin('~/.vim/plugged')

Plug 'preservim/nerdtree'
Plug 'joshdick/onedark.vim'
Plug 'itchyny/lightline.vim'
Plug 'mattn/emmet-vim'
Plug 'tpope/vim-surround'
Plug 'vim-scripts/AutoClose'
Plug 'posva/vim-vue'

Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'

Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'honza/vim-snippets'

Plug 'christoomey/vim-system-copy'

call plug#end()

source ~/.vim/settings/coc.vim
source ~/.vim/settings/nerdtree.vim
source ~/.vim/settings/lightline.vim

"FZF bindings
map <C-f> :Files! <CR>

"theme
colorscheme onedark

"vim settings
filetype plugin indent on
syntax on
set tabstop=4 shiftwidth=4 expandtab 
set hidden
set backspace=start,eol,indent
set nu rnu
set incsearch
set nowrap
set noswapfile
set spell
set spelllang=en_us,de_de
set cursorline

set path=.,**

" Disable arrow movement, resize splits instead.
nnoremap <Up>    :resize +2<CR>
nnoremap <Down>  :resize -2<CR>
nnoremap <Left>  :vertical resize +2<CR>
nnoremap <Right> :vertical resize -2<CR>

" Navigate split buffers
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" Shift lines in visual mode
xnoremap K :move '<-2<CR>gv-gv
xnoremap J :move '>+1<CR>gv-gv
