"Vim rc

"Plug 
call plug#begin('~/.vim/plugged')

Plug 'preservim/nerdtree'
Plug 'joshdick/onedark.vim'
Plug 'itchyny/lightline.vim'
Plug 'mattn/emmet-vim'
Plug 'tpope/vim-surround'
Plug 'vim-scripts/AutoClose'

Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'honza/vim-snippets'

call plug#end()

source ~/.vim/settings/coc.vim
source ~/.vim/settings/nerdtree.vim
source ~/.vim/settings/lightline.vim

"theme
colorscheme onedark

"vim settings
filetype plugin indent on
syntax on
set tabstop=4 shiftwidth=4 expandtab 
set hidden
set backspace=start,eol,indent
set nu rnu
set incsearch
set noswapfile
set spell
set spelllang=en_us,de_de
set cursorline

set path=.,**

" Disable arrow movement, resize splits instead.
nnoremap <Up>    :resize +2<CR>
nnoremap <Down>  :resize -2<CR>
nnoremap <Left>  :vertical resize +2<CR>
nnoremap <Right> :vertical resize -2<CR>

" Navigate split buffers
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" Shift lines in visual mode
xnoremap K :move '<-2<CR>gv-gv
xnoremap J :move '>+1<CR>gv-gv
